Refactor pipeline to accomodate EKS testing
* DNS for the cluster now happens with terraform
* Need to pass CLUSTER_TYPE in many tasks

Co-authored-by: Kieron Browne <kbrowne@vmware.com>

diff --git a/pipelines/scripts/common/gcloud-functions b/pipelines/scripts/common/gcloud-functions
--- a/pipelines/scripts/common/gcloud-functions
+++ b/pipelines/scripts/common/gcloud-functions
@@ -8,9 +8,20 @@ gcloud-login() {
 }
 
 export-kubeconfig() {
-  gcloud-login
-  declare -r name=$1
-  gcloud container clusters get-credentials "$name" --zone "$GCP_ZONE"
-  echo "$GCP_SERVICE_ACCOUNT_JSON" >"/tmp/sa.json"
-  export GOOGLE_APPLICATION_CREDENTIALS="/tmp/sa.json"
+  case "$CLUSTER_TYPE" in
+    "GKE")
+      gcloud-login
+      gcloud container clusters get-credentials "$CLUSTER_NAME" --zone "$GCP_ZONE"
+      echo "$GCP_SERVICE_ACCOUNT_JSON" >"/tmp/sa.json"
+      export GOOGLE_APPLICATION_CREDENTIALS="/tmp/sa.json"
+      ;;
+    "EKS")
+      aws eks update-kubeconfig --region "$AWS_REGION" --name "$CLUSTER_NAME"
+      ;;
+    *)
+      echo "Invalid CLUSTER_TYPE: $CLUSTER_TYPE"
+      echo "Valid values are: EKS, GKE"
+      exit 1
+      ;;
+  esac
 }
